app/models/gene.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 19-8-5 
# @Author  : JiaoJianglong

from app.extensions import mongo


class Transcripts():

    def __init__(self):
        self.conn = mongo.db.transcripts

    def insert(self, vals):

        self.conn.insert_many(vals)

app/templates/__init__.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 19-8-3 
# @Author  : JiaoJianglong

app/views/gene.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 19-8-4 
# @Author  : JiaoJianglong


import re
import requests
from bs4 import BeautifulSoup

from flask import Blueprint, request, render_template, views
from flask_login import login_required

from app.extensions import mongo

gene = Blueprint('gene', __name__)


@gene.route("/message/", methods=["GET", "POST"])
@login_required
def message():
    if request.method == "POST":
        search_text = request.values.get("message")
        limit = int(request.values.get("limit", "10"))
        offset = int(request.values.get("offset", "0"))
        res = requests.get(
            "https://asia.ensembl.org/Multi/Ajax/search?q=(+{0}%5E316+AND+species%3A%22CrossSpecies%22+)"
            "+OR+(+{0}%5E190+AND+species%3A%22Human%22+)+OR+(+{0}%5E80+AND+species%3A%22Mouse%22+)"
            "+OR+(+{0}+AND+species%3A%22Zebrafish%22+)"
            "&fq=(++(++species%3A%22CrossSpecies%22+AND+(+reference_strain%3A1+)++)"
            "++OR++(++species%3A%22Human%22+AND+(+reference_strain%3A1+)++)"
            "++OR++(++species%3A%22Mouse%22+AND+(+reference_strain%3A1+)++)"
            "++OR++(++species%3A%22Zebrafish%22+AND+(+reference_strain%3A1+)++)++)"
            "&hl=true&hl.fl=_hr&hl.fl=content&hl.fl=description&hl.fragsize=500&rows={1}&start={2}"
                .format(search_text, limit, offset)).json()
        response = res.get('result', {}).get("response", {})
        response['total'] = response.get("numFound")
        return response
    return render_template("gene.html")


@gene.route("/transcripts/", methods=["GET", "POST"])
@login_required
def transcripts():
    def parse(value):
        base_url = "https://asia.ensembl.org"
        new_value = {}
        for key, td in value.items():
            try:
                if key == "Name":
                    new_value[key] = td.text
                # elif key == "Translation ID":
                #     new_value[key] = td.a.text
                elif key == "Transcript ID":
                    new_value[key] = {"text": td.a.text, "url": base_url+td.a.attrs["href"]}
                    new_value["_id"] = td.a.text
                elif key == "bp":
                    new_value[key] = td.text
                elif key == "Protein":
                    new_value[key] = {"text": td.a.text, "url": td.a.attrs["href"]}
                elif key == "Biotype":
                    if td.find("span", class_="_ht_tip"):
                        note = td.find("span", class_="_ht_tip").text
                        text = td.find("span", class_="ht _ht").text.replace(note, "")
                    else:
                        text = td.find("div", class_="coltab-text").text
                        note = None
                    color = td.find("span", class_="coltab-tab").attrs["style"]
                    color = re.search(r"background-color:(.*);", color).group(1)
                    new_value[key] = {"text": text, "note": note, "color": color}

                elif key == "CCDS":
                    new_value[key] = {"text": td.a.text, "url": td.a.attrs["href"]}
                elif key == "UniProt":
                    new_value[key] = {"text": td.a.text, "url": td.a.attrs["href"]}
                elif key == "RefSeq Match":
                    new_value[key] = {"text": td.a.text, "url": td.a.attrs["href"]}

                elif key == "Flags":
                    flags = []
                    for span in td.find_all("span", class_="ts_flag"):
                        note = span.find("span", class_="_ht_tip").text
                        text = span.find("span", class_="ht _ht").text.replace(note, "")
                        flags.append({"text": text, "note": note})
                    new_value[key] = flags
            except:
                new_value[key] = None
        return new_value

    suc_result = {"data": "", "code": 200, "msg": "请求成功"}
    if request.method == "GET":
        domain = request.values.get("domain")
        domain_url = request.values.get("domain_url")

        res = requests.get(domain + "/" + domain_url)
        soup = BeautifulSoup(res.text, 'lxml')
        transcripts_table = soup.find(id='transcripts_table')

        keys = [th.text for th in transcripts_table.thead.tr.find_all("th")]
        values = [dict(zip(keys, [td for td in tr.find_all("td")])) for tr in transcripts_table.tbody.find_all("tr")]

        suc_result['data'] = [parse(value) for value in values]

        mongo.db.transcripts.insert_many(suc_result['data'])
        return suc_result

app/views/users.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 19-8-3 
# @Author  : JiaoJianglong


from flask import Blueprint, redirect, render_template, flash, url_for, request
from flask_login import login_required, login_user, logout_user

from app.models.user import User
from app.extensions import login_manager, db
from app.forms.user import RegisterForm, LoginForm

users = Blueprint('users', __name__)


@login_manager.user_loader
def load_user(uid):
    return User.query.get(uid)


@users.route('/register/', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        user = User(username=form.username.data, password=form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('注册成功')
        return redirect(url_for('users.login'))

    return render_template('register.html', form=form)


@users.route('/login/', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        username = form.username.data
        user = User.query.filter(User.username == username).first()
        if not user:
            flash('用户名或密码错误')
        elif not user.verify_password(form.password.data):
            flash('用户名或密码错误')
        else:
            login_user(user, remember=form.remember.data)
            flash('登录成功')
            return redirect(url_for('gene.message', next=request.args.get('next')))
    return render_template('login.html', form=form)


@users.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for('users.login'))

app/templates/gene.html
{% extends 'bootstrap/base.html' %}

{% block title %}基因资讯{% endblock %}

{% block styles %}
{{ super() }}
<link rel="stylesheet" href="/static/css/bootstrap-table.min.css">
{% endblock %}

{% block navbar %}
<nav class="navbar navbar-default" style="border-radius: 0px;">
  <div class="container">

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-left">
        {% if current_user.is_authenticated %}
        <li style="line-height: 50px">
          <input style="display: inline-block" type="text" class="form-control search-input"
                 placeholder="Search" aria-label="Search"
                 aria-describedby="basic-addon2">
        </li>
        <li style="line-height: 50px">
          <button class="btn btn-outline-secondary" type="button" onclick="search()">Search</button>
        </li>
        {% endif %}
      </ul>
      <ul class="nav navbar-nav navbar-right">
        {% if current_user.is_authenticated %}
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
             aria-haspopup="true"
             aria-expanded="false">选项</a>
          <ul class="dropdown-menu">
            <li><a href="{{ url_for('users.logout') }}">退出</a></li>
          </ul>
        </li>

        {% else %}
        <li><a href="{{ url_for('users.login') }}">登录</a></li>
        <li><a href="{{ url_for('users.register') }}">注册</a></li>
        {% endif %}


      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
{% endblock %}

{% block content %}
<div class="container">
  {% for message in get_flashed_messages() %}
  <div class="alert alert-success alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
        aria-hidden="true">&times;</span></button>
    <strong>{{ message }}</strong>
  </div>
  {% endfor %}
  {% block page_content %}
  <table id="gene_list" data-toggle="table">
    <thead>
    <tr>
      <th data-field="name">Name</th>
      <th data-field="description">Description</th>
    </tr>
    </thead>
  </table>
  <table id="transcripts" data-toggle="table">
    <thead>
    <tr>
      <th data-field="Name">Name</th>
      <th data-field="Transcript ID" data-formatter="ProteinFormat">Transcript ID</th>
      <th data-field="bp">bp</th>
      <th data-field="Protein" data-formatter="ProteinFormat">Protein</th>
      <!--<th data-field="Translation ID">Translation ID</th>-->
      <th data-field="Biotype" data-formatter="BiotypeFormat">Biotype</th>
      <th data-field="CCDS" data-formatter="ProteinFormat">CCDS</th>
      <th data-field="UniProt" data-formatter="ProteinFormat">UniProt</th>
      <th data-field="RefSeq Match" data-formatter="ProteinFormat">RefSeq Match</th>
      <th data-field="Flags" data-formatter="FlagsFormat">Flags</th>
    </tr>
    </thead>
  </table>
  {% endblock %}
</div>
{% endblock %}

{% block scripts %}
{{super()}}

<script>
  function search() {
    var search_text = $(".search-input").val();
    $.ajax({
      type: "post",
      dataType: "html",
      url: '/gene/message/',
      data: {message: search_text},
      success: function (data) {
        if (data) {
          var data = $.parseJSON(data);
          var docs = data["docs"];
          $('#gene_list').bootstrapTable("load", docs);
          $('#gene_list').bootstrapTable('refresh');
        }
      }
    });
  }

  function FlagsFormat(value, row, index) {
    var html = "";
    for(i=0;i<value.length;i++){
      html = html+"<span " +
          "style='display: inline-block;margin: 0 6px;background-color: #eeeeee'>" +
          value[i].text + "</span>";
    }
    return html
  }
  function BiotypeFormat(value, row, index){
    var html = "<div style='width:5px;height:20px;" +
        "display:inline-block; margin: 0 5px; background-color: "+value.color +
        "'></div><span>" + value.text + "</span>";
    return html
  }
  function ProteinFormat(value, row, index){
    if(value){
      html = "<a href='"+ value.url +"'>"+value.text+"</a>";
      return html
    }
    return value
  }

  function initTable() {
    $("#gene_list").bootstrapTable({
      method: 'post',
      contentType: "application/x-www-form-urlencoded",
      url: '/gene/message/',
      dataField: "docs",
      dataType: "json",
      pagination: true,
      pageSize: 5,
      pageNumber: 1,
      pageList: [5, 10, 15, 20],
      sidePagination: 'server',
      queryParams: queryParams,
      singleSelect: true,
      onClickRow: ClickRow,
    });
  }

  function ClickRow(row, $element) {
    $("#transcripts").bootstrapTable('removeAll');
    $.ajax({
      type: "get",
      dataType: "html",
      url: '/gene/transcripts/',
      data: row,
      success: function (data) {
        if (data) {
          var data = $.parseJSON(data);
          $('#transcripts').bootstrapTable("load", data.data);
        }
      }
    });
  }

  function queryParams(params) {
    var search_value = $(".search-input").val();
    return {
      message: search_value,
      limit: params.limit,
      offset: params.offset,
    }
  }

  $(document).ready(function () {
    initTable();
    window.setTimeout(function () {
      $('[data-dismiss="alert"]').alert('close');
    }, 2000);

  });


</script>
<script src="/static/js/bootstrap-table.min.js"></script>
{% endblock %}

app/templates/login.html
{% extends 'bootstrap/base.html' %}

{% import 'bootstrap/wtf.html' as wtf %}

{% block title %}用户登录{% endblock %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet" href="/static/css/login.css">
{% endblock %}


{% block content %}

<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
            aria-hidden="true">&times;</span></button>
        <strong>{{ message }}</strong>
    </div>
    {% endfor %}
    {% block page_content %}
    <div id="login">
        <h1 align="center">用户登录</h1>
        <hr>
        {{ wtf.quick_form(form,button_map={'submit':'primary'}) }}
        <div>
            <div style="margin-top: 5px"><span>没有账号？<a href="{{ url_for('users.register') }}">立即注册</a></span></div>

        </div>
    </div>
    {% endblock %}
</div>

{% endblock %}

{% block scripts %}
{{super()}}
{% endblock %}

app/templates/register.html
{% extends 'bootstrap/base.html' %}

{% import 'bootstrap/wtf.html' as wtf %}

{% block title %}用户登录{% endblock %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet"href="/static/css/login.css">
{% endblock %}


{% block content %}

<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
            aria-hidden="true">&times;</span></button>
        <strong>{{ message }}</strong>
    </div>
    {% endfor %}
    {% block page_content %}
    <div id="login">
        <h1 align="center">用户注册</h1>
        <hr>
        {{ wtf.quick_form(form,button_map={'submit':'primary'}) }}
        <div align="center">
            <a href="{{ url_for('users.login') }}">已有账号登录</a>
        </div>
    </div>
    {% endblock %}
</div>

{% endblock %}

{% block scripts %}
{{super()}}
{% endblock %}